{
 "title": "Orka Overview",
 "description": "Orka Overview",
 "tags": [
  "orka",
  "overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(up{job=\"orka-nodes\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Orka NSF Share Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (device) (node_filesystem_size_bytes{fstype=\"nfs\"} - node_filesystem_avail_bytes{fstype=\"nfs\"})) by (device)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (device) (node_filesystem_avail_bytes{fstype=\"nfs\"})) by (device)",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Worker Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"orka-nodes\"} == 1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(up{job=\"orka-nodes\"} == 0) or vector(0)",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "count(up{job=\"orka-nodes\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orka_operator_virtual_machine_instances_total",
     "legendFormat": "VM Instances"
    },
    {
     "expr": "orka_operator_apple_silicon_virtual_machine_instances_total",
     "legendFormat": "Apple Silicon VMs"
    },
    {
     "expr": "orka_operator_intel_virtual_machine_instances_total",
     "legendFormat": "Intel VMs"
    }
   ]
  },
  {
   "title": "Orka API IP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"orka-server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "up{job=\"orka-nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Orka API requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(orka_server_http_requests_total{route=~\"/resources/.*\"}[1m]))",
     "legendFormat": "API requests/s"
    }
   ]
  }
 ]
}